export const SKILLS_FIND_ALL_START = 'SKILLS_FIND_ALL_START';
export const SKILLS_FIND_ALL_OK = 'SKILLS_FIND_ALL_OK';
export const SKILLS_FIND_ALL_NOK = 'SKILLS_FIND_ALL_NOK';

export const SKILL_SAVE_START = 'SKILL_SAVE_START';
export const SKILL_SAVE_OK = 'SKILL_SAVE_OK';
export const SKILL_SAVE_NOK = 'SKILL_SAVE_NOK';
export const SKILL_SAVE_VOID = 'SKILL_SAVE_VOID';

export const SKILL_EDIT_START = 'SKILL_EDIT_START';
export const SKILL_EDIT_OK = 'SKILL_EDIT_OK';
export const SKILL_EDIT_NOK = 'SKILL_EDIT_NOK';

export const SKILL_DELETE_START = 'SKILL_DELETE_START';
export const SKILL_DELETE_OK = 'SKILL_DELETE_OK';
export const SKILL_DELETE_NOK = 'SKILL_DELETE_NOK';