export const SKILLS_FIND_ALL_START = 'SKILLS_FIND_ALL_START';
export const SKILLS_FIND_ALL_OK = 'SKILLS_FIND_ALL_OK';
export const SKILLS_FIND_ALL_NOK = 'SKILLS_FIND_ALL_NOK';

export const SKILL_SAVE_START = 'SKILL_SAVE_START';
export const SKILL_SAVE_OK = 'SKILL_SAVE_OK';
export const SKILL_SAVE_NOK = 'SKILL_SAVE_NOK';
export const SKILL_SAVE_VOID = 'SKILL_SAVE_VOID';

export const SKILLS_UPDATE_BYID = 'SKILLS_UPDATE_BYID';
export const SKILLS_DELETE_BYID = 'SKILLS_DELETE_BYID';
export const SKILLS_INCREASE_COUNTER = 'SKILLS_INCREASE_COUNTER';