export const SKILLS_FIND_ALL = 'SKILLS_FIND_ALL';
export const SKILLS_CREATE_SKILL = 'SKILLS_CREATE_SKILL';
export const SKILLS_UPDATE_BYID = 'SKILLS_UPDATE_BYID';
export const SKILLS_DELETE_BYID = 'SKILLS_DELETE_BYID';
export const SKILLS_INCREASE_COUNTER = 'SKILLS_INCREASE_COUNTER';